### ISSUE TITLE
Container won't start

### ISSUE THREAD

**Issue by bqbn** [mozilla-services/poucave#123]
Using mozilla/poucave:1.3.1 image, the container won't start with the following error:

```
$ kubectl logs stage-poucave-app-1-deploy-6789b75db6-kzl5v poucave
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "poucave/__main__.py", line 5, in <module>
    main(sys.argv[1:])
  File "/app/poucave/main.py", line 208, in main
    app = init_app(conf)
  File "/app/poucave/main.py", line 149, in init_app
    handler = handlers.checkpoint(project, check, **params)
  File "/app/poucave/main.py", line 60, in checkpoint
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/checks/remotesettings/validate_signatures.py", line 14, in <module>
    import cryptography.x509
  File "/usr/local/lib/python3.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509 import certificate_transparency
  File "/usr/local/lib/python3.7/site-packages/cryptography/x509/certificate_transparency.py", line 10, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

It looks like the `six` module is missing inside the image.

**Comment by leplatrem** [comment]
Wao, that's weird, since we run the tests from the container on each commit.
And I can see on CircleCI that `six` gets installed. https://circleci.com/gh/mozilla-services/poucave/313#tests/containers/0

I'll investigate...

**Comment by leplatrem** [comment]
The situation is the following:
- we install the remotesettings checks with `--no-deps` because we don't want kinto-signer to pull Pyramid, Kinto, since we just need `canonical_json()` (see https://github.com/mozilla-services/remote-settings-lambdas/issues/44 BTW)
- `six` is a sub-dependency of `cryptography` and `unidecode` one of `kinto_http`
- when we run the tests we [install on-the-go](https://github.com/mozilla-services/poucave/blob/5485235f24b7bf1fc031943f56200d80736e935b/scripts/run.sh#L9-L18) the dev dependencies
- but `six` is also a dependency of `aioresponses` and `unidecode` was listed as dev dep, so the issue was masked :) 

Solutions are:
- list `six` and `unidecode` as explicit dependencies of `remotesettings`
- install kinto-signer with all dependencies
- extract canical json in a library instead of installer kinto-signer
